export const languages = {
  English: {
    nav: {
      home: "Home",
      questions: "Questions",
      theme: "Theme",
      submit: "Submit",
      hide: "Hide",
      show: "Show",
      statistics: "Statistics",
      accountSettings: "Settings",
    },
    login: {
      login: "Log In",
      password: "password",
      or: "or",
      signinWith: "Sign in with",
      forgotPassword: "Forgot password?",
      needAccount: "Need an account?",
      singup: "Sign Up",
      loginFail: "Failed to Login",
    },
    forgotPassword: {
      oups: "Oups...",
      resetPassword: "Reset Password",
      login: "Log In",
      needAccount: "Need an account?",
      singup: "Sign Up",
      sendingEmail: "Sending email",
      checkEmail: "Check your email",
      failSend: "Failed to send",
    },
    singup: {
      singup: "Sign Up",
      alreadyHaveAccount: "Already have an account?",
      login: "Log In",
      password: "password",
      confirmPassword: "confirm password",
      passwordNoMatch: "Passwords don't match",
      failToCreate: "Failed to create account",
      passwordMinChars: "Password should at least 6 characters",
      wait: "Please wait",
      accountCreated: "Account created",
      mailInUse: "Email already in use",
    },
    resetProfile: {
      minPass: "Password should at least 6 characters",
      passwordNoMatch: "Password does not match",
      setNewPassword: "Set new password",
      back: "Back",
      expriedLink: "The link has expired",
      wrong: "Oups... Something went wrong",
      resetPassword: "Reset Password",
      wait: "Please wait...",
      redirect: "Redirecting...",
      failed: "Failed to reset",
    },
    confirmBox: {
      noUndo: "This action is irreversible cannot be undone!",
      areYouSure: "Are you sure?",
      cancel: "Cancel",
      delete: "Delete",
    },
  },

  Ελληνικά: {
    nav: {
      home: "Αρχική",
      questions: "Ερωτήσεις",
      theme: "Θέμα",
      submit: "Υποβολή",
      hide: "Απόκρηψη",
      show: "Εμφάνιση",
      statistics: "Στατιστικά",
      accountSettings: "Ρυθμίσεις",
    },
    login: {
      login: "Είσοδος",
      password: "κωδικός",
      or: "ή",
      signinWith: "Είσοδος με",
      forgotPassword: "Ξεχάσατε τον κωδικό;",
      needAccount: "Δεν έχετε λογαριασμό;",
      singup: "Εγγραφή",
      loginFail: "Αποτυχία εισόδου",
    },
    forgotPassword: {
      oups: "Ουπς...",
      resetPassword: "Επαναφορά Κωδικού",
      login: "Είσοδος",
      needAccount: "Δεν έχετε λογαριασμό;",
      singup: "Εγγραφή",
      sendingEmail: "Αποστολή email",
      checkEmail: "Ελέγξτε το email σας",
      failSend: "Αποτυχία αποστολής",
    },
    singup: {
      singup: "Εγγραφή",
      alreadyHaveAccount: "Έχετε ήδη λογαριασμό;",
      login: "Είσοδος",
      password: "κωδικός",
      confirmPassword: "επιβεβαίωση κωδικού",
      passwordNoMatch: "Οι κωδικοί δεν ταιριάζουν",
      failToCreate: "Αποτυχία δημιουργίας λογαριασμού",
      passwordMinChars: "Ο κωδικός πρέπει να είναι πάνω απο 6 χαρακτήρες",
      wait: "Παρακαλώ περιμένετε",
      accountCreated: "Ο λογαρισμός δημιουργήθηκε",
      mailInUse: "Το email χρησιμοποιείτε ήδη",
    },
    resetProfile: {
      minPass: "Ο κωδικός πρέπει να έχει ελάχιστους 6 χαρακτήρες",
      passwordNoMatch: "Οι κώδικοι δεν είναι ίδιοι",
      setNewPassword: "Ορισμός νέου κωδικόυ",
      back: "Πίσω",
      expriedLink: "Ο σύνδεσμος έχει λήξει",
      wrong: "Ουπς... Κάτι πήγε στραβά",
      resetPassword: "Επαναφορά Κωδικόυ",
      wait: "Παρακαλώ περιμένετε...",
      redirect: "Ανακατεύθυνση...",
      failed: "Αποτυχία επαναφοράς",
    },
    confirmBox: {
      noUndo: "Αυτή η κίνηση δεν μπορεί να αναιρεθεί!",
      areYouSure: "Είστε σίγουροι;",
      cancel: "Ακύρωση",
      delete: "Διαγραφή",
    },
  },
};
